<?php

namespace IdnoPlugins\ActivityPub\Pages;

use IdnoPlugins\ActivityPub\ActivityBuilder;

/**
 * Serves QuoteAuthorization stamps for quote post verification (FEP-044f).
 *
 * Remote servers fetch this endpoint to verify that a quote was authorized
 * by the quoted post's author. The stamp URL contains the interaction target,
 * interacting object, and an HMAC signature to prevent forgery.
 *
 * Route: /activitypub/quote-stamp?target=...&object=...&sig=...
 */
class QuoteStamp extends \Idno\Common\Page
{

    function getContent()
    {
        $target = $this->getInput('target', '');
        $object = $this->getInput('object', '');
        $sig = $this->getInput('sig', '');

        if (empty($target) || empty($object) || empty($sig)) {
            $this->setResponse(400);
            http_response_code(400);
            header('Content-Type: application/json');
            echo json_encode(['error' => 'Missing parameters']);
            exit;
        }

        // Verify HMAC to ensure this stamp URL was generated by us
        $secret = \Idno\Core\Idno::site()->config()->site_secret ?? \Idno\Core\Idno::site()->config()->getDisplayURL();
        $expectedSig = hash_hmac('sha256', $target . "\n" . $object, $secret);

        if (!hash_equals($expectedSig, $sig)) {
            $this->setResponse(404);
            http_response_code(404);
            header('Content-Type: application/json');
            echo json_encode(['error' => 'Not found']);
            exit;
        }

        // Look up the quoted entity to find its author
        $entity = \Idno\Common\Entity::getByUUID($target);
        if (!$entity) {
            $entity = \Idno\Common\Entity::getBySlug($target);
        }

        $attributedTo = '';
        if ($entity) {
            $owner = $entity->getOwner();
            if ($owner) {
                $attributedTo = $owner->getActivityPubActorID();
            }
        }

        $siteUrl = \Idno\Core\Idno::site()->config()->getDisplayURL();
        $stampUrl = $siteUrl . 'activitypub/quote-stamp'
            . '?target=' . urlencode($target)
            . '&object=' . urlencode($object)
            . '&sig=' . $sig;

        $stamp = [
            '@context' => ActivityBuilder::CONTEXT_WITH_QUOTES,
            'type'     => 'QuoteAuthorization',
            'id'       => $stampUrl,
            'interactionTarget' => $target,
            'interactingObject' => $object,
        ];

        if (!empty($attributedTo)) {
            $stamp['attributedTo'] = $attributedTo;
        }

        header('Content-Type: application/activity+json');
        header('Access-Control-Allow-Origin: *');
        header('Cache-Control: max-age=3600, public');
        echo json_encode($stamp, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT);
        exit;
    }

    function postContent()
    {
        $this->setResponse(405);
        http_response_code(405);
        header('Content-Type: application/json');
        header('Allow: GET');
        echo json_encode(['error' => 'Method not allowed']);
        exit;
    }
}
