<ul class="nav nav-tabs">
  <li <?php if (\Idno\Core\Idno::site()->currentPage()->doesPathMatch('/admin/')) echo 'class="active"'; ?> role="presentation"><a href="<?=\Idno\Core\Idno::site()->config()->getDisplayURL()?>admin/"><?= \Idno\Core\Idno::site()->language()->_('Site configuration'); ?></a></li>
  <li <?php if (\Idno\Core\Idno::site()->currentPage()->doesPathMatch('/admin/plugins/')) echo 'class="active"'; ?> role="presentation"><a href="<?=\Idno\Core\Idno::site()->config()->getDisplayURL()?>admin/plugins/"><?= \Idno\Core\Idno::site()->language()->_('Plugins'); ?></a></li>
  <li <?php if (\Idno\Core\Idno::site()->currentPage()->doesPathMatch('/admin/themes/')) echo 'class="active"'; ?> role="presentation"><a href="<?=\Idno\Core\Idno::site()->config()->getDisplayURL()?>admin/themes/"><?= \Idno\Core\Idno::site()->language()->_('Themes'); ?></a></li>
            <?=$this->draw('admin/menu/items')?>
  <li <?php if (\Idno\Core\Idno::site()->currentPage()->doesPathMatch('/admin/homepage/')) echo 'class="active"'; ?> role="presentation"><a href="<?=\Idno\Core\Idno::site()->config()->getDisplayURL()?>admin/homepage/" ><?= \Idno\Core\Idno::site()->language()->_('Homepage'); ?></a></li>
  <li <?php if (\Idno\Core\Idno::site()->currentPage()->doesPathMatch('/admin/email/')) echo 'class="active"'; ?> role="presentation"><a href="<?=\Idno\Core\Idno::site()->config()->getDisplayURL()?>admin/email/" ><?= \Idno\Core\Idno::site()->language()->_('Email'); ?></a></li>
  <li <?php if (\Idno\Core\Idno::site()->currentPage()->doesPathMatch('/admin/users/')) echo 'class="active"'; ?> role="presentation"><a href="<?=\Idno\Core\Idno::site()->config()->getDisplayURL()?>admin/users/" ><?= \Idno\Core\Idno::site()->language()->_('Users'); ?></a></li>
  <li <?php if (\Idno\Core\Idno::site()->currentPage()->doesPathMatch('/admin/export/')) echo 'class="active"'; ?> role="presentation"><a href="<?=\Idno\Core\Idno::site()->config()->getDisplayURL()?>admin/export/" ><?= \Idno\Core\Idno::site()->language()->_('Export'); ?></a></li>
  <li <?php if (\Idno\Core\Idno::site()->currentPage()->doesPathMatch('/admin/import/')) echo 'class="active"'; ?> role="presentation"><a href="<?=\Idno\Core\Idno::site()->config()->getDisplayURL()?>admin/import/" ><?= \Idno\Core\Idno::site()->language()->_('Import'); ?></a></li>
  <li <?php if (\Idno\Core\Idno::site()->currentPage()->doesPathMatch('/admin/statistics/')) echo 'class="active"'; ?> role="presentation"><a href="<?=\Idno\Core\Idno::site()->config()->getDisplayURL()?>admin/statistics/"><?= \Idno\Core\Idno::site()->language()->_('Statistics'); ?></a></li>
  <li <?php if (\Idno\Core\Idno::site()->currentPage()->doesPathMatch('/admin/diagnostics/')) echo 'class="active"'; ?> role="presentation"><a href="<?=\Idno\Core\Idno::site()->config()->getDisplayURL()?>admin/diagnostics/"><?= \Idno\Core\Idno::site()->language()->_('Diagnostics'); ?></a></li>
  <?php if (!empty(\Idno\Core\Idno::site()->config()->capture_logs) && \Idno\Core\Idno::site()->config()->capture_logs) { ?>
    <li <?php if (\Idno\Core\Idno::site()->currentPage()->doesPathMatch('/admin/logs/')) echo 'class="active"'; ?> role="presentation"><a href="<?=\Idno\Core\Idno::site()->config()->getDisplayURL()?>admin/logs/"><?= \Idno\Core\Idno::site()->language()->_('Captured Logs'); ?></a></li>
  <?php } ?>
  <li <?php if (\Idno\Core\Idno::site()->currentPage()->doesPathMatch('/admin/about/')) echo 'class="active"'; ?> role="presentation"><a href="<?=\Idno\Core\Idno::site()->config()->getDisplayURL()?>admin/about/"><?= \Idno\Core\Idno::site()->language()->_('About'); ?></a></li>
</ul>
